# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b405d45978c87f37071e55181611e048af31defbe8589cadf739b36dd6a2aec643f30af3c1de73d9fcff1758f58aa7f292096965c9ca77eeb42da3eeb52ee026

test:
  secret_key_base: d147cfda9680b6797044c3b681a66c73686bb19639809dee06c5ef2229ae74eb2e6a46de36dac742b8f70986b8663328eee92e09833bed6164fb9b55f62d5806

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
